"""
sandbox_api.py — Secure Mathematical Execution Sandbox

A minimalist FastAPI server that accepts Python code strings submitted by the
Judge Agent, executes them inside a tight subprocess timeout, and returns the
deterministic stdout output. The sandbox has no internet access (enforced at
the Docker network layer) and runs as an unprivileged user.

Constitutional contract: this service MAY ONLY execute code that has been
generated by the Judge Agent as validation_code. It must never be directly
user-facing.
"""

import subprocess
import sys
import textwrap
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="Constitutional Math Sandbox", version="2.0.0")


class ExecutionRequest(BaseModel):
    code: str
    timeout_seconds: int = 10  # Hard ceiling — prevent runaway computation


class ExecutionResult(BaseModel):
    stdout: str
    stderr: str
    exit_code: int
    verified: bool  # True iff exit_code == 0 and stderr is empty


@app.get("/health")
def health() -> dict:
    """Liveness probe used by docker-compose and Makefile verify-sandbox."""
    return {"status": "ok", "service": "constitutional_sandbox"}


@app.post("/execute", response_model=ExecutionResult)
def execute(request: ExecutionRequest) -> ExecutionResult:
    """
    Execute a Python code string in a sandboxed subprocess.

    Security constraints (enforced here and at the Docker layer):
    - Subprocess inherits NO environment variables that contain secrets.
    - Hard timeout prevents infinite loops or resource exhaustion.
    - stderr is captured; any exception propagated back to the Judge Agent.
    - No network calls can succeed (Docker internal_mesh has no egress).
    """
    if not request.code or not request.code.strip():
        raise HTTPException(status_code=400, detail="Empty code payload rejected.")

    # Dedent to tolerate multi-line strings passed from the LangGraph engine
    code = textwrap.dedent(request.code)

    try:
        result = subprocess.run(
            [sys.executable, "-c", code],
            capture_output=True,
            text=True,
            timeout=request.timeout_seconds,
            env={},  # Strip all env — no secrets, no PATH surprises
        )
    except subprocess.TimeoutExpired:
        raise HTTPException(
            status_code=408,
            detail=f"Execution timed out after {request.timeout_seconds}s. "
                   "Mathematical validation must be deterministic and fast.",
        )

    return ExecutionResult(
        stdout=result.stdout.strip(),
        stderr=result.stderr.strip(),
        exit_code=result.returncode,
        verified=(result.returncode == 0 and not result.stderr.strip()),
    )
